
spring:
    datasource:
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
        driverClassName: com.mysql.jdbc.Driver
        filters: stat,wall,log4j
        initialSize: 5
        maxActive: 20
        maxPoolPreparedStatementPerConnectionSize: 20
        maxWait: 60000
        minEvictableIdleTimeMillis: 300000
        minIdle: 5
        password: JZdev@2018
        poolPreparedStatements: true
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://192.168.1.77:3306/doctordb_dev?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
        useGlobalDataSourceStat: true
        username: jzdev1
        validationQuery: SELECT 1 FROM DUAL
    redis:
      database: 0
      host: 118.126.91.137
      port: 6379
      password: a66666666
      jedis:
        pool:
          max-active: 10
          max-wait: -1
          max-idle: 8
          min-idle: 0
      timeout: 10000
#    thymeleaf:
#      cache: false
#      prefix: classpath:/templates/
#      encoding: utf-8
#      servlet:
#        content-type: text/html
#      mode: HTML5
    devtools:
      restart:
        enabled: true

#mybatis:
#  # \u6307\u5B9A\u5168\u5C40\u914D\u7F6E\u6587\u4EF6\u4F4D\u7F6E
#  config-location: classpath:mapper/mybatis-config.xml
#  # \u6307\u5B9Asql\u6620\u5C04\u6587\u4EF6\u4F4D\u7F6E
#  mapper-locations: classpath:mapper/*Mapper.xml


mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.login.demo
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0s
    logic-not-delete-value: 1
    #自定义SQL注入器
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
server:
  port: 9000
security:
  basic:
    enabled: false


jwt:
   secret: mySecret
   expiration: 259200
   tokenHead: Bearer
   header: Authorization
   route:
    authentication:
     path: auth/login
     refresh: auth/refresh
     register: auth/register"

sms:
   expiration: 180
logging:
  path: D:\java\log
